name: first-interaction

on:
  issues:
    types: [opened]
  pull_request:
    branches: [main]
    types: [opened]

jobs:
  check_for_first_interaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/first-interaction@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Welcome @${{ github.actor }} and thank you for raising an issue! The team was notified and will get back to you as soon as possible.
            
            Please confirm that the issue you are raising does not already exist. Do not forget to leave us a Star if you have not yet. Thank you.
          pr-message: |
            Welcome @${{ github.actor }} and thank you for creating a Pull Request! The team was notified and will get back to you as soon as possible.
            
            Do not forget to leave us a Star if you have not yet. Thank you."
